protocol_chunks = [
    {"title": "Persistent cough duration threshold",
     "text": "A cough lasting more than three weeks should be medically evaluated. Persistent cough is one of the most common warning signs associated with lung cancer.",
     "cancer_types": ["lung"]},
    {"title": "Hemoptysis referral urgency",
     "text": "Coughing up blood is a major warning sign that requires urgent medical attention. Even small amounts of blood in sputum should not be ignored because it may indicate a serious underlying condition.",
     "cancer_types": ["lung"]},
    {"title": "Smoking as primary risk factor",
     "text": "Smoking is the leading preventable risk factor for lung cancer. Current and long-term smokers have a significantly higher risk than people who have never smoked.",
     "cancer_types": ["lung"]},
    {"title": "Family history significance (lung)",
     "text": "People with a family history of lung cancer may have a higher risk of developing the disease. Family history should be considered alongside other risk factors and symptoms.",
     "cancer_types": ["lung"]},
    {"title": "Occupational exposure risks",
     "text": "Long-term exposure to harmful substances such as asbestos, silica dust, diesel exhaust, and certain industrial chemicals can increase lung cancer risk. Occupational history is an important part of risk assessment.",
     "cancer_types": ["lung"]},
    {"title": "Lung cancer screening age guidance",
     "text": "The risk of lung cancer generally increases with age. Most cases are diagnosed in older adults, making age an important factor during screening and risk evaluation.",
     "cancer_types": ["lung"]},
    {"title": "Difficulty swallowing as a secondary but important symptom",
     "text": "Difficulty swallowing may occur in some patients with advanced chest diseases, including lung cancer. Persistent swallowing problems should be medically evaluated, especially when accompanied by other symptoms.",
     "cancer_types": ["lung", "oral"]},
    {"title": "Neck swelling and spread indicators",
     "text": "Swelling or lumps around the neck or collarbone area can sometimes indicate enlarged lymph nodes. When present with respiratory or oral symptoms, further medical evaluation may be needed.",
     "cancer_types": ["lung", "oral"]},
    {"title": "Smoking cessation",
     "text": "Stopping smoking is one of the most effective ways to reduce lung and oral cancer risk. Health benefits begin soon after quitting and continue to increase over time.",
     "cancer_types": ["lung", "oral"]},

    {"title": "Breast lump duration threshold",
     "text": "A breast lump or thickening that persists beyond a few weeks should be clinically evaluated, even if it is painless. A painless lump is not necessarily benign and still requires assessment.",
     "cancer_types": ["breast"]},
    {"title": "Nipple discharge and skin changes",
     "text": "Nipple discharge, especially if blood-stained or spontaneous, and skin changes such as dimpling, puckering, or nipple retraction are warning signs that warrant a clinical breast examination.",
     "cancer_types": ["breast"]},
    {"title": "Family history significance (breast)",
     "text": "Having a first-degree relative, such as a mother, sister, or daughter, with breast cancer meaningfully increases individual risk and should be factored into screening frequency.",
     "cancer_types": ["breast"]},
    {"title": "Breast cancer age and screening guidance",
     "text": "Breast cancer risk rises noticeably after age 40. Clinical breast examination alongside mammography is recommended at regular intervals from this age onward.",
     "cancer_types": ["breast"]},
    {"title": "Breast cancer high-risk referral",
     "text": "A persistent lump, nipple changes, or the combination of multiple risk factors should prompt referral for diagnostic mammography or ultrasound without delay.",
     "cancer_types": ["breast"]},

    {"title": "Persistent mouth ulcer or sore",
     "text": "A mouth ulcer or sore that does not heal within three weeks should be evaluated by a dentist or doctor, particularly in people who use tobacco.",
     "cancer_types": ["oral"]},
    {"title": "Red or white oral patches",
     "text": "Red or white patches inside the mouth, known as erythroplakia or leukoplakia, can be early and potentially precancerous changes and should not be ignored even when painless.",
     "cancer_types": ["oral"]},
    {"title": "Tobacco and areca nut risk",
     "text": "Chewing tobacco, gutka, and areca nut (paan) use are the leading risk factors for oral cancer in India, and risk increases substantially when combined with alcohol use.",
     "cancer_types": ["oral"]},
    {"title": "Oral cancer age and exposure duration guidance",
     "text": "Oral cancer risk increases with age and with the cumulative duration of tobacco or areca nut use, making long-term users a priority group for screening.",
     "cancer_types": ["oral"]},

    {"title": "Abnormal vaginal bleeding threshold",
     "text": "Bleeding between periods, after intercourse, or after menopause is not normal and should be evaluated promptly, since it is a key warning sign for cervical abnormalities.",
     "cancer_types": ["cervical"]},
    {"title": "HPV as primary risk factor",
     "text": "Persistent infection with high-risk HPV types is the primary cause of cervical cancer. An HPV-positive result increases the importance of staying on schedule with regular screening.",
     "cancer_types": ["cervical"]},
    {"title": "Cervical screening interval guidance",
     "text": "Regular Pap smear or HPV testing, generally recommended between ages 30 and 65, is one of the most effective ways to detect precancerous changes before they progress.",
     "cancer_types": ["cervical"]},
    {"title": "Abnormal discharge and pelvic pain",
     "text": "Persistent abnormal vaginal discharge or pelvic pain, especially alongside irregular bleeding, warrants gynecological evaluation.",
     "cancer_types": ["cervical"]},
    {"title": "Overdue screening risk",
     "text": "Being overdue for cervical screening raises the risk of late detection, since early cervical changes often produce no noticeable symptoms.",
     "cancer_types": ["cervical"]},

    {"title": "High risk referral guidance",
     "text": "Individuals with multiple risk factors or serious warning signs should seek prompt medical evaluation. Early referral helps ensure timely diagnosis and treatment, regardless of cancer type.",
     "cancer_types": ["general"]},
    {"title": "Medium risk follow up",
     "text": "Individuals with moderate risk factors should schedule a routine medical consultation. Symptoms that persist or worsen over time should not be ignored.",
     "cancer_types": ["general"]},
    {"title": "Low risk guidance",
     "text": "A low risk assessment does not completely rule out disease. Individuals should continue monitoring symptoms and seek medical advice if new concerns develop.",
     "cancer_types": ["general"]},
]